### ISSUE TITLE
general todo list

### ISSUE THREAD

**Issue by flashwave** [flashwave/maki#1]
- [ ] queue web requests globally
- [ ] merge structs and classes with some better serialisation trickery
- [ ] make everything not bad
